### ISSUE TITLE
psycopg2-py37:2 in us-east-1...no permissions from us-east-1 account?!

### ISSUE THREAD

**Issue by DarrinTisdale** [jetbridge/psycopg2-lambda-layer#10]
I've gone through and confirmed that the user account has full rights to perform the action and that the account used is in `us-east-1`. When I perform simply try to access the version information, I receive:

`An error occurred (AccessDeniedException) when calling the GetLayerVersion operation: User: arn:aws:iam::XXXXXXXXXXXX:user/XXXXXX-service is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-east-1:898466741470:layer:psycopg2-py37:2`

My DevOps guys tells me I am doing it correctly, so  what's up?

**Comment by revmischa** [comment]
Can you try `arn:aws:lambda:us-east-1:898466741470:layer:psycopg2-py37:3`?

**Comment by szicari-farmobile** [comment]
@revmischa I just confirmed that `arn:aws:lambda:us-east-1:898466741470:layer:psycopg2-py37:3` _does_ work.

**Comment by cjstudioz** [comment]
Merry Xmas, any chance you could do the same for region ap-southeast-1 3.7 please I'm still getting the error above for this.
arn:aws:lambda:ap-southeast-1:898466741470:layer:psycopg2-py37

**Comment by revmischa** [comment]
> 

Please try using `arn:aws:lambda:ap-southeast-1:898466741470:layer:psycopg2-py37:6`

**Comment by cjstudioz** [comment]
thank you, that works now
