### ISSUE TITLE
Are you able to provide instructions how you compiled these layers?

### ISSUE THREAD

**Issue by alanwill** [jetbridge/psycopg2-lambda-layer#14]
I'd like to create one for Py3.8

**Comment by revmischa** [comment]
The source to compile them is in the repo, you can use that. I can add py3.8 no problem. What region would you like it in?

**Comment by revmischa** [comment]
https://github.com/jetbridge/psycopg2-lambda-layer/blob/master/3.8/build.sh is how it is built
