### ISSUE TITLE
Would like a Python 3.8 psycopg2 layer for us-east-1

### ISSUE THREAD

**Issue by tzaffi** [jetbridge/psycopg2-lambda-layer#16]
Just requesting an updated version of `arn:aws:lambda:us-east-1:898466741470:layer:psycopg2-py37:3`

Thank you!

**Comment by revmischa** [comment]
Sure please give `arn:aws:lambda:us-east-1:898466741470:layer:psycopg2-py38:1` a try

**Comment by tzaffi** [comment]
much appreciated
