### ISSUE TITLE
US East 2, please

### ISSUE THREAD

**Issue by gclabbe-sundanceenergy** [jetbridge/psycopg2-lambda-layer#19]
And thank you

":^)

**Comment by andybarr-lp** [comment]
Adding another vote to this one!

**Comment by revmischa** [comment]
Which python?

**Comment by andybarr-lp** [comment]
My need is for Python 3.6.0

On Tue, Nov 3, 2020 at 4:40 AM Mischa Spiegelmock <notifications@github.com>
wrote:

> Which python?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jetbridge_psycopg2-2Dlambda-2Dlayer_issues_19-23issuecomment-2D721091858&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=cjCyuwoUuDPwljqBF9EiGY4otznvK-e1x0yNn3brmOY&m=BdYahuD11eBQd-gslM5xJ6Rihl7-OfLPCk-z254aUAg&s=9dlDOOSyK-VHNgpJwYvG3rA_0fQFZm28mHwwuKfTz2Y&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AJ5XS3AQ73F2UUIWPJX7UWTSN722LANCNFSM4RQXKXWQ&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=cjCyuwoUuDPwljqBF9EiGY4otznvK-e1x0yNn3brmOY&m=BdYahuD11eBQd-gslM5xJ6Rihl7-OfLPCk-z254aUAg&s=zWylezZfK3KHXdqurBwZUwlm1OALYF9Fy603_uNPUmo&e=>
> .
>

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Comment by revmischa** [comment]
Ok try out `arn:aws:lambda:us-east-2:898466741470:layer:psycopg2-py36:1`
Python 3.9 is out now! Upgrade today!

**Comment by andybarr-lp** [comment]
Amazing! Thank you very much.

**Comment by gclabbe-sundanceenergy** [comment]
Awesome!

We are mostly using 3.7 with AWS pushing hard for everyone to move to 3.8.

Since it's the base for SQLAlchemy … and a major feature of the AWS platform is PostgreSQL, would be awesome to see this module included in the normal builds.


[cid:79302989-5f5e-4674-ab6a-c522ab3afdc5]
________________________________
