### ISSUE TITLE
permissions on version 1 for python 3.8 us-east-1 are wrong

### ISSUE THREAD

**Issue by mloudon** [jetbridge/psycopg2-lambda-layer#23]
arn:aws:lambda:us-east-1:898466741470:layer:psycopg2-py38:1 doesn't work, arn:aws:lambda:us-east-1:898466741470:layer:psycopg2-py38:2 does

**Comment by revmischa** [comment]
Ok fixed thx! https://github.com/jetbridge/psycopg2-lambda-layer/commit/d7cda3c6e0d5a4ba01922e8fbce26dfe4809621f
