### ISSUE TITLE
I am getting a permissions erros on arn:aws:lambda:us-west-2:898466741470:layer:psycopg2-py37:6

### ISSUE THREAD

**Issue by ricksturgeon** [jetbridge/psycopg2-lambda-layer#26]
I am getting a permissions error on arn:aws:lambda:us-west-2:898466741470:layer:psycopg2-py37:6, I just noticed it yesterday. Have used with not issues in the past. 

User: arn:aws:iam::***MYUserId** is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-west-2:898466741470:layer:psycopg2-py37:6 (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 252ed721-a226-4e96-add3-94e587e8413a; Proxy: null)

Also console error "you are not authorized to perform: lambda:GetLayerVersion" when logged into Oregan US-West-2, Also added additional permissions for GetLayerVersion, but user has full Lambda access and always worked before. Could it be from the recent updates you made?

**Comment by luisesantos** [comment]
@ricksturgeon I am getting exactly the same issue on the same layer. Any ideas of why this is happening ?
`arn:aws:lambda:us-west-2:898466741470:layer:psycopg2-py37:6`

**Comment by revmischa** [comment]
Sorry, I really don't know why this would have started happening. I uploaded a new layer at 
`arn:aws:lambda:us-west-2:898466741470:layer:psycopg2-py37:7` -does that solve your issue?

**Comment by luisesantos** [comment]
@revmischa thanks a lot ... it did solve the issue.

**Comment by ricksturgeon** [comment]
👍

**Comment by ricksturgeon** [comment]
I actually upgraded my lambdas to python 3.8 as recommended by AWS support.
