### ISSUE TITLE
No layer for py-3.8 in eu-west-2

### ISSUE THREAD

**Issue by matiassciencenow** [jetbridge/psycopg2-lambda-layer#28]
psycopg2-lambda-layer is available for py3.8 in many regions but not in eu-west-2. It would be great to have it here.

Thank you very much,
Matias.

**Comment by revmischa** [comment]
Ok try `arn:aws:lambda:eu-west-2:898466741470:layer:psycopg2-py38:1`

**Comment by matiassciencenow** [comment]
Thank you very much!
