### ISSUE TITLE
request support for eu-west-1 (DUB)

### ISSUE THREAD

**Issue by rstrahan** [jetbridge/psycopg2-lambda-layer#3]
Hi.. support for eu-west-1 (DUB) would be very cool. Thanks!

**Comment by revmischa** [comment]
Ok try arn:aws:lambda:eu-west-1:178183757879:layer:psycopg2-py37:1
Cheers!

**Comment by rstrahan** [comment]
awesome - works like a charm. Thanks @revmischa !
