### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by quiver** [jetbridge/psycopg2-lambda-layer#31]
AWS Lambda supports Python 3.9 in all regions where Lambda is available from Mid August 2021.

[AWS Lambda adds support for Python 3.9](https://aws.amazon.com/about-aws/whats-new/2021/08/aws-lambda-adds-support-python-3-9/)

Can you consider to provide 3.9 Layers?

**Comment by revmischa** [comment]
Sure, what region do you need it in?

**Comment by quiver** [comment]
> Sure, what region do you need it in?

eu-central-1

**Comment by bahoo** [comment]
Can I throw a vote / request behind us-west-2 ? 🙏 Thank you !

**Comment by quiver** [comment]
I think supporting all regions as 3.8 from the start will decrease your workload.

**Comment by revmischa** [comment]
Might need to wait for `docker.io/lambci/lambda:build-python3.9` to exist

**Comment by quiver** [comment]
There exists an issue for lambci/lambda:build-python3.9 support.

lambci/issues#138

**Comment by Malikx-Alee** [comment]
Can we now get the support for python 3.9 of this layer is us-east-2?

**Comment by revmischa** [comment]
We need a docker image to build it with. See https://github.com/lambci/docker-lambda/pull/348 
Feel free to send a PR with support for 3.9

**Comment by jpb8** [comment]
Support for python 3.9 us-east-2 would be appreciated

**Comment by hassanejaz** [comment]
eu-west-3 please 🙏 Thank you !

**Comment by samunstein** [comment]
The lambci repository has been inactive, but there is a fork with python3.9 support at https://github.com/mLupine/docker-lambda (discussed here https://github.com/lambci/docker-lambda/issues/353#issuecomment-943301567). Could that be just switched in instead?

**Comment by mswezey23** [comment]
> The lambci repository has been inactive, but there is a fork with python3.9 support at https://github.com/mLupine/docker-lambda (discussed here [lambci/docker-lambda#353 (comment)](https://github.com/lambci/docker-lambda/issues/353#issuecomment-943301567)). Could that be just switched in instead?

That should be sufficient. I've used that specific one for python 3.9 in AWS lambdas w/ successful results

**Comment by revmischa** [comment]
Cool, I invite anyone to fork this and build for 3.9. Open a PR with your lambda layer ARNs.

**Comment by revmischa** [comment]
New layers:
```
      # py 3.9:
      - arn:aws:lambda:us-east-1:898466741470:layer:psycopg2-py39:1
      - arn:aws:lambda:us-east-2:898466741470:layer:psycopg2-py39:1
      - arn:aws:lambda:us-west-1:898466741470:layer:psycopg2-py39:1
      - arn:aws:lambda:us-west-2:898466741470:layer:psycopg2-py39:1
      - arn:aws:lambda:ca-central-1:898466741470:layer:psycopg2-py39:1
      - arn:aws:lambda:eu-west-1:898466741470:layer:psycopg2-py39:1
      - arn:aws:lambda:eu-west-2:898466741470:layer:psycopg2-py39:1
      - arn:aws:lambda:eu-west-3:898466741470:layer:psycopg2-py39:1
      - arn:aws:lambda:eu-central-1:898466741470:layer:psycopg2-py39:1
```
