### ISSUE TITLE
Why doesn't supporting regions for GOV cloud (us-gov-east-1 and us-gov-west-1), Can u add supporting for these regions 

### ISSUE THREAD

**Issue by ananhagyahya** [jetbridge/psycopg2-lambda-layer#34]

**Comment by revmischa** [comment]
How?

**Comment by ananhagyahya** [comment]
we already using it in us-east-1 and its working.we tried to use in us-gov-east-1 region but its not supported.the arn in Gov cloud should be start with arn:aws-gov-us:........ and not arn:aws:.....Sent on the go with SamsungNote
-------- Original message --------From: Mischa Spiegelmock ***@***.***> Date: 12/4/21  4:25 PM  (GMT+02:00) To: jetbridge/psycopg2-lambda-layer ***@***.***> Cc: Anan ***@***.***>, Author ***@***.***> Subject: Re: [jetbridge/psycopg2-lambda-layer] Why doesn't supporting regions for GOV cloud (us-gov-east-1 and us-gov-west-1), Can u add supporting for these regions  (Issue #34) 
How?

**Comment by ananhagyahya** [comment]
For AWS GovCloud the region is changed to be : us-gov-west-1 and us-gov-east-1 
also the ARNs in GovCloud are not the same all ARNs started with arn:aws-us-gov not like AWS standard accounts.

So Can we have another new paths for GovCloud regions ? 

Thanks

**Comment by revmischa** [comment]
Any idea how to deploy to govcloud with serverless?
```
➜  3.7 git:(master) ✗ sls deploy -r us-gov-east-1
Serverless: Configuration warning at 'layers['psycopg2-py37']': unrecognized property 'buildScript'
Serverless:
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:
Serverless: Packaging service...
Serverless: Excluding development dependencies...

 Serverless Error ----------------------------------------

  The security token included in the request is invalid.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.17.5
     Framework Version:         2.69.1
     Plugin Version:            5.5.1
     SDK Version:               4.3.0
     Components Version:        3.18.1
```

I suggest building the layer yourself using this repo and upload your own layer. 

Do you think they let people share layers in govcloud? 

Why are you asking some random goofball like me to provide you code to run your govcloud database workloads? Maybe that's not the most secure approach?
