### ISSUE TITLE
Request for us-west-2 for python 3.7

### ISSUE THREAD

**Issue by johncolmdoyle** [jetbridge/psycopg2-lambda-layer#5]
Would it be possible to get a layer for us-west-2?

**Comment by revmischa** [comment]
sure pay me $5

**Comment by revmischa** [comment]
just kidding. try `arn:aws:lambda:us-west-2:898466741470:layer:psycopg2-py37:6`

**Comment by johncolmdoyle** [comment]
Cheers!
