### ISSUE TITLE
AccessDenied even though I am on the same region

### ISSUE THREAD

**Issue by fletling** [jetbridge/psycopg2-lambda-layer#8]
When I run `aws lambda get-layer-version --layer-name arn:aws:lambda:eu-central-1:898466741470:layer:psycopg2-py37 --version-number 2 --region eu-central-1` I get 

`An error occurred (AccessDeniedException) when calling the GetLayerVersion operation: User: XXX is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:eu-central-1:898466741470:layer:psycopg2-py37:2`

I tried the same with different regions as well, same result. Also same result when I attempt to use the layer in a cloudformation template. 

Any hints?

**Comment by revmischa** [comment]
Try `aws lambda get-layer-version --layer-name arn:aws:lambda:eu-central-1:898466741470:layer:psycopg2-py37 --version-number 6 --region eu-central-1`
thanks - updated readme

**Comment by fletling** [comment]
awesome! Thanks for the quick help =)

**Comment by rasnick** [comment]
I'm trying to use ```arn:aws:lambda:us-east-2:898466741470:layer:psycopg2-py37:1``` and I'm getting the same error: ```You are not authorized to perform: lambda:GetLayerVersion```.
I'm on us-east-2 region, already tried using other versions (2 to 6) just in case but no luck.

**Comment by revmischa** [comment]
@rasnick try `arn:aws:lambda:us-east-2:898466741470:layer:psycopg2-py37:1` now?

**Comment by rasnick** [comment]
@revmischa works perfectly now, thanks!
