### ISSUE TITLE
Request for ap-southeast-2 for python 3.7

### ISSUE THREAD

**Issue by roiavidan** [jetbridge/psycopg2-lambda-layer#9]
Hi.
Would it be possible to get the Python 3.7 layer in ap-southeast-2 (Sydney)?

Thanks a lot!

**Comment by revmischa** [comment]
Okay, give `arn:aws:lambda:ap-southeast-2:898466741470:layer:psycopg2-py37:1` a try

**Comment by roiavidan** [comment]
Thanks @revmischa !! 👍
